      - name: Build APK
        run: gradle assembleDebug --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Easy-MikroTik-APK
          path: app/build/outputs/apk/debug/*.apk
