name: Check Project Structure

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List Files
        run: |
          echo "=========== ROOT DIRECTORY ==========="
          ls -la
          echo "=========== SEARCHING FOR GRADLE ==========="
          find . -name "build.gradle*" -maxdepth 3
          echo "=========== SEARCHING FOR PACKAGE.JSON ==========="
          find . -name "package.json" -maxdepth 3
